### ISSUE TITLE
The duplicate warning/error will output for every 5 seconds.

### ISSUE THREAD

**Issue by nick-wang** [ClusterLabs/hawk-apiserver#11]
Will output "Failed to connect to Pacemaker: -107: ENOTCONN Transport endpoint is not connected" for every 5 secs if pacemaker is stopped. Similar issues like "Failed to query CIB" and "Failed to subscribe"

Unnecessary to output the duplicate warning, or have a threshold for the numbers.

**Comment by nick-wang** [comment]
Since 5 seconds is a short time, it is easy to reach the threshold of same output. Personally i prefer avoid output the same message.
I create a [pr](https://github.com/krig/hawk-apiserver/pull/12) to explain what i mean.

**Comment by krig** [comment]
Closing since the PR was merged. Thank you!
