### ISSUE TITLE
feature: Unix socket reverse proxy support

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/hawk-apiserver#32]
this was originatelly from Readme.md

@krig  maybe you could add more inside infos here. 

( I plan to remove the todos from readme.md)

**Comment by krig** [comment]
Ah this one is actually done! This is how the API server communicates with the hawk backend now.

See https://github.com/ClusterLabs/hawk-apiserver/blob/master/server/reverseproxy.go#L161
