### ISSUE TITLE
[Question] Is this project still under active maintainance

### ISSUE THREAD

**Issue by imjoey** [ClusterLabs/hawk-apiserver#45]
Hi maintainers, I was wondering that if we are still actively developing this project, cause the last commit was on one year ago. May I ask that what the roadmap is for the future releases? Thanks.

**Comment by diegoakechi** [comment]
@imjoey Yes, this is still maintained, but the roadmap currently is under revision about next improvements we want to do for HAWK. Currently hawk-apiserver has a very limited and stable scope (serve as reverse-proxy for HAWK) and therefore has not been demanding much.

**Comment by imjoey** [comment]
@diegoakechi thank you for the explanation and very glad to see this. This project is awesome and looking forward to its release iterations. Thanks again for this great work and hopefully we could also take part in the community development. Let's close this issue.

**Comment by diegoakechi** [comment]
@imjoey Thanks for the feedback! Contributions are always welcomed in any of our projects, like HAWK, crmsh, ha_cluster_exporter, pacemaker, etc.
